apiVersion: v1
kind: Namespace
metadata:
  name: dvwa

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
  namespace: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: docker.io/library/mydvwa:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  namespace: dvwa
spec:
  selector:
    app: dvwa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
